//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension ___VARIABLE_MODULENAME___View.Action {
    var feature: ___VARIABLE_MODULENAME___Action {
        switch self {
        case .onAppear:
            return .onAppear
        }
    }
}
